// Optional local-only browser test. Requires Playwright + Chrome, static frontend on :3000,
// API on :8000; build with the synthetic project.example.test auth env in docs.
const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
let exchangeCount=0;
const demo=await page.request.post('http://localhost:8000/auth/login',{data:{phone:'9000000001',password:'demo1234'}});const demoToken=(await demo.json()).token;
await page.route('https://project.example.test/**',async route=>{
 const req=route.request(); const url=req.url();
 if(req.method()==='OPTIONS')return route.fulfill({status:200,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*','Access-Control-Allow-Methods':'*'}});
 if(url.includes('/auth/v1/authorize'))return route.fulfill({status:302,headers:{location:'http://localhost:3000/login#error=access_denied&error_description=cancelled'}});
 return route.fulfill({status:200,headers:{'Access-Control-Allow-Origin':'*'},contentType:'application/json',body:'{}'});
});
await page.route('**/auth/supabase', async route=>{exchangeCount++;const body=route.request().postDataJSON();if(!body.consent)return route.fulfill({status:422,contentType:'application/json',body:JSON.stringify({detail:'Consent is required to create an account'})});if(exchangeCount>=3)return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({token:demoToken})});return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Identity verification is temporarily unavailable'})});});
for(const width of [390,320]){await page.setViewportSize({width,height:844});await page.goto('http://localhost:3000/login');await page.getByRole('button',{name:'Continue with Google'}).waitFor();await page.screenshot({path:`/downloads/ct-google-login-${width}.png`,fullPage:true});console.log('login',width,'overflow',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));}
await page.getByRole('button',{name:'Continue with Google'}).click();await page.getByRole('status').waitFor();console.log('consent guard',await page.getByRole('status').innerText());await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Continue with Google'}).click();await page.waitForURL('**/login#error*');await page.getByText('Sign-in was cancelled or could not be completed. Please try again.').waitFor();console.log('cancel error cleaned',await page.url());
// Synthetic Supabase browser session simulates a magic-link/OAuth return in a new tab.
await page.evaluate(()=>{const payload=btoa(JSON.stringify({sub:'test-user',aud:'authenticated',exp:Math.floor(Date.now()/1000)+3600})).replace(/=/g,'');localStorage.setItem('sb-project-auth-token',JSON.stringify({access_token:'e30.'+payload+'.test',refresh_token:'test-refresh',token_type:'bearer',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,user:{id:'test-user',aud:'authenticated',role:'authenticated',email:'synthetic@example.test',app_metadata:{provider:'google'},user_metadata:{name:'Synthetic'}}}));sessionStorage.removeItem('ct:auth-consent');});
await page.reload();await page.getByRole('button',{name:'Finish sign-in'}).waitFor();console.log('new-tab consent guard',await page.getByRole('button',{name:'Finish sign-in'}).isDisabled());await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Finish sign-in'}).click();await page.getByText('Unable to finish sign-in. Try again or use phone and password.').waitFor();await page.screenshot({path:'/tmp/ct-google-error-320.png',fullPage:true});console.log('retry failure retained',exchangeCount);await page.getByRole('button',{name:'Finish sign-in'}).click();await page.waitForURL('http://localhost:3000/');await page.getByRole('heading',{name:'Anjali',exact:true}).waitFor();console.log('successful exchange routes home',exchangeCount);await page.goto('http://localhost:3000/login');await page.getByLabel('Phone number',{exact:true}).fill('wrong');await page.getByLabel('Password',{exact:true}).fill('wrong');await page.getByRole('button',{name:'Log in',exact:true}).click();await page.getByText(/Wrong phone or password/).waitFor();console.log('wrong phone login stays on page',await page.url(),'errors',errors);await browser.close();})();
